### ISSUE TITLE
[Bug]: FiveM Arm64 Version

### ISSUE THREAD

**Issue by Helpme0822** [QuintenQVD0/Q_eggs#109] opened 2024-04-20 20:28 UTC
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

FiveM Arm64 Version

### Modified

No, I did not modify the egg

### Expected Behavior

Launch server and have no error message appear in the console.

### Actual Behavior

This error keeps getting spammed every 5 minutes in my server console :

Server list query returned an error: Interop+Crypto+OpenSslCryptographicException: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac <- Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. <- System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. <- System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

Any idea on how to fix it? I didn't modify your egg and I also use a domain which has a ssl certificate.

![image](https://github.com/QuintenQVD0/Q_eggs/assets/36854248/4ff9530b-05b1-48f2-a59a-54bac50ef1d7)

### Steps To Reproduce

Just install the server normally using your Egg then launch it and then this message should appear every like 3-5 minutes in the console.

### Install logs

https://pteropaste.com/y5qg/

**Comment by Helpme0822** [comment] 2024-04-21 22:23
I just figured out that this error has something to do with my server also not showing up in the server browser.

This usually occurs when the ports are not opened but I'm 100% sure that my ports are opened since I can successfully access the server and txAdmin on another PC on another network. So yeah I'm not sure what is causing this but everything should be fine on my VPS where the server is hosted on.

**Comment by QuintenQVD0** [comment] 2024-04-22 07:08
To be honnest I have no idea what this would cause. If you have at least 2 ports allocated and you use the main port in the txadmin config to setup the server then it works for me.

**Comment by Helpme0822** [comment] 2024-04-22 14:43
I have both ports 30120 and 40120 allocated and I'm able to enter both the server and the txadmin from another network. The ip that I need to use for the allocation is the one called "Private IP" in Oracle cloud right?

**Comment by QuintenQVD0** [comment] 2024-04-22 14:49
> I have both ports 30120 and 40120 allocated and I'm able to enter both the server and the txadmin from another network. The ip that I need to use for the allocation is the one called "Private IP" in Oracle cloud right?

yes, but everywhere elese in the configs its 0.0.0.0

**Comment by Helpme0822** [comment] 2024-04-22 14:57
> > I have both ports 30120 and 40120 allocated and I'm able to enter both the server and the txadmin from another network. The ip that I need to use for the allocation is the one called "Private IP" in Oracle cloud right?
> 
> yes, but everywhere elese in the configs its 0.0.0.0

if you mean in the server.cfg yeah there it's still on 0.0.0.0

**Comment by Helpme0822** [comment] 2024-04-22 14:59
do you want me to maybe send screenshot of like all the config stuff of the server to see if there's maybe something I did wrong?

**Comment by Helpme0822** [comment] 2024-04-22 15:11
> > do you want me to maybe send screenshots of like all the config stuff of the server to see if there's maybe something I did wrong?
> 
> It should be fine, as long as the config in txadmin has the right port it should work.

where exactly do I check the port on txadmin just to be sure?

**Comment by Helpme0822** [comment] 2024-04-22 15:17
is it this?

![image](https://github.com/QuintenQVD0/Q_eggs/assets/36854248/4432ab0d-9c38-407c-a51f-565d1bcb3539)

**Comment by QuintenQVD0** [comment] 2024-04-22 15:51
> > > do you want me to maybe send screenshots of like all the config stuff of the server to see if there's maybe something I did wrong?
> > 
> > 
> > It should be fine, as long as the config in txadmin has the right port it should work.
> 
> where exactly do I check the port on txadmin just to be sure?

at the top, their should a tcp and udp bind address

**Comment by Helpme0822** [comment] 2024-04-22 15:55
> > is it this?
> > ![image](https://private-user-images.githubusercontent.com/36854248/324516004-4432ab0d-9c38-407c-a51f-565d1bcb3539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDEzNDksIm5iZiI6MTcxMzgwMTA0OSwicGF0aCI6Ii8zNjg1NDI0OC8zMjQ1MTYwMDQtNDQzMmFiMGQtOWMzOC00MDdjLWE1MWYtNTY1ZDFiY2IzNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzY5MDVlZTcwNDM2MzdhN2E3ZTUxYTU4ZTQ1OTNkZDQ1ZGExYmU5NTZhZTE4MDZhNjA4NzQ1MmZhNjIyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r9EpJtlwhlVCkfNLcwL3T8pRRfNI4BecsutZxaDTAHU)
> 
> that could also be wrong indeed

I checked on another server that I got running on windows and it shows the same there too tho so I don't think that's the issue unfortunately

**Comment by QuintenQVD0** [comment] 2024-04-22 15:55
> > > > > do you want me to maybe send screenshots of like all the config stuff of the server to see if there's maybe something I did wrong?
> > > > 
> > > > 
> > > > It should be fine, as long as the config in txadmin has the right port it should work.
> > > 
> > > 
> > > where exactly do I check the port on txadmin just to be sure?
> > 
> > 
> > at the top, their should a tcp and udp bind address
> 
> do you mean this in the server.cfg ?
> 
> ![image](https://private-user-images.githubusercontent.com/36854248/324527673-da36c923-1b0a-4970-b2f6-be499e965415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE1OTksIm5iZiI6MTcxMzgwMTI5OSwicGF0aCI6Ii8zNjg1NDI0OC8zMjQ1Mjc2NzMtZGEzNmM5MjMtMWIwYS00OTcwLWIyZjYtYmU0OTllOTY1NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZDdiODdlYmQ1YmY2ZTllM2RkNjJkOTU3ODA3OTg5NjMzZmNmNjJmZmFlYWEzNmJiNDdlZTUxOTc2Y2IyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIMJ3eHqvHe75rEbCG9eZ4KG1UUQNJVN2kTcGXCJ7Yk)
> 
> Or if you just mean like the url then yeah it's the right ip/domain with the right port.



> > > > > do you want me to maybe send screenshots of like all the config stuff of the server to see if there's maybe something I did wrong?
> > > > 
> > > > 
> > > > It should be fine, as long as the config in txadmin has the right port it should work.
> > > 
> > > 
> > > where exactly do I check the port on txadmin just to be sure?
> > 
> > 
> > at the top, their should a tcp and udp bind address
> 
> do you mean this in the server.cfg ?
> 
> ![image](https://private-user-images.githubusercontent.com/36854248/324527673-da36c923-1b0a-4970-b2f6-be499e965415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE1OTksIm5iZiI6MTcxMzgwMTI5OSwicGF0aCI6Ii8zNjg1NDI0OC8zMjQ1Mjc2NzMtZGEzNmM5MjMtMWIwYS00OTcwLWIyZjYtYmU0OTllOTY1NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZDdiODdlYmQ1YmY2ZTllM2RkNjJkOTU3ODA3OTg5NjMzZmNmNjJmZmFlYWEzNmJiNDdlZTUxOTc2Y2IyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIMJ3eHqvHe75rEbCG9eZ4KG1UUQNJVN2kTcGXCJ7Yk)
> 
> Or if you just mean like the url then yeah it's the right ip/domain with the right port.

thats fine and indeed how it should be.

**Comment by Helpme0822** [comment] 2024-04-22 16:17
Here's also the list of all the ports I got open/forwarded on both the server with the panel and the server with the wings :

![image](https://github.com/QuintenQVD0/Q_eggs/assets/36854248/7d7ae1a2-6774-44fe-9df0-fe7182f62a8a)

Those same ports are also opened/forwarded on the Oracle cloud interface in the security list. Let me know if I'm maybe missing one that could be maybe causing the issue.

**Comment by Helpme0822** [comment] 2024-04-22 16:45
![image](https://github.com/QuintenQVD0/Q_eggs/assets/36854248/d4a0e20e-2786-4d0e-9d06-4cc788fe770d)

Could the steam user not being set or the app ID not being set maybe somehow causing the issue?

**Comment by QuintenQVD0** [comment] 2024-04-22 16:54
> ![image](https://private-user-images.githubusercontent.com/36854248/324542234-d4a0e20e-2786-4d0e-9d06-4cc788fe770d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDUxNTEsIm5iZiI6MTcxMzgwNDg1MSwicGF0aCI6Ii8zNjg1NDI0OC8zMjQ1NDIyMzQtZDRhMGUyMGUtMjc4Ni00ZDBlLTlkMDYtNGNjNzg4ZmU3NzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2NTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMzc1MWM3ZTExYWJmNTA5OTVmM2FmMDNmNmYyYmUxMGRhNDA3YmEzMDkyNDE2ZWUwMzdlZWIyZjg3OGI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1TpU_tc1yD0psC_k3gtvHmpCzEgC-bA7HNfqMqcyMqA)
> 
> Could the steam user not being set or the app ID not being set maybe somehow causing the issue?

thats not an issue, thats just because that is not a steamcmd game

**Comment by Helpme0822** [comment] 2024-04-22 17:08
I also just created a new fivem server on pterodactyl again and noticed that the default RootFS used is ubuntu 20.04. The one I use on the oracle vps tho is ubuntu 22.04. Could that maybe be the issue?

Also btw I used this pterodactyl installer to install pterodactyl on the oracle cloud VPS:

https://github.com/pterodactyl-installer/pterodactyl-installer

Could this maybe be causing the issue?

**Comment by QuintenQVD0** [comment] 2024-04-22 17:28
> I also just created a new fivem server on pterodactyl again and noticed that the default RootFS used is ubuntu 20.04. The one I use on the oracle vps tho is ubuntu 22.04. Could that maybe be the issue?
> 
> Also btw I used this pterodactyl installer to install pterodactyl on the oracle cloud VPS:
> 
> https://github.com/pterodactyl-installer/pterodactyl-installer
> 
> Could this maybe be causing the issue?

its not supported, but you got i running so it should not be.

and the mismatch in rootfs is not an issue at all

**Comment by Helpme0822** [comment] 2024-04-22 17:34
> > I also just created a new fivem server on pterodactyl again and noticed that the default RootFS used is ubuntu 20.04. The one I use on the oracle vps tho is ubuntu 22.04. Could that maybe be the issue?
> > Also btw I used this pterodactyl installer to install pterodactyl on the oracle cloud VPS:
> > https://github.com/pterodactyl-installer/pterodactyl-installer
> > Could this maybe be causing the issue?
> 
> its not supported, but you got i running so it should not be.
> 
> and the mismatch in rootfs is not an issue at all

do you use any installer to install pterodactyl or do you just follow their documentation?

**Comment by QuintenQVD0** [comment] 2024-04-22 17:50
> > > I also just created a new fivem server on pterodactyl again and noticed that the default RootFS used is ubuntu 20.04. The one I use on the oracle vps tho is ubuntu 22.04. Could that maybe be the issue?
> > > Also btw I used this pterodactyl installer to install pterodactyl on the oracle cloud VPS:
> > > https://github.com/pterodactyl-installer/pterodactyl-installer
> > > Could this maybe be causing the issue?
> > 
> > 
> > its not supported, but you got i running so it should not be.
> > and the mismatch in rootfs is not an issue at all
> 
> do you use any installer to install pterodactyl or do you just follow their documentation?

docs

**Comment by Helpme0822** [comment] 2024-04-22 18:01
> > > > I also just created a new fivem server on pterodactyl again and noticed that the default RootFS used is ubuntu 20.04. The one I use on the oracle vps tho is ubuntu 22.04. Could that maybe be the issue?
> > > > Also btw I used this pterodactyl installer to install pterodactyl on the oracle cloud VPS:
> > > > https://github.com/pterodactyl-installer/pterodactyl-installer
> > > > Could this maybe be causing the issue?
> > > 
> > > 
> > > its not supported, but you got i running so it should not be.
> > > and the mismatch in rootfs is not an issue at all
> > 
> > 
> > do you use any installer to install pterodactyl or do you just follow their documentation?
> 
> docs

could you maybe try if by using the installer I used your fivem server also works and doesn't get the error if you have time? Since I guess that would be faster than me following the docs.

But if you don't have time then I get that and will try and reinstall everything by following the docs

**Comment by Helpme0822** [comment] 2024-04-22 18:07
btw I used a separate normal amd free oracle server to install the panel using the installer I sent and then installed the wings on the arm64 oracle server using the same installer

**Comment by Helpme0822** [comment] 2024-04-22 21:05
I just installed it by following the docs and have both the panel and wings on the same vps and I'm still getting the same error message in the console 😭

**Comment by Helpme0822** [comment] 2024-04-28 14:33
@QuintenQVD0 btw which OS do you use? Do you use ubuntu as well? Since I was thinking that maybe this could be causing my issue?

**Comment by QuintenQVD0** [comment] 2024-04-28 14:34
> @QuintenQVD0 btw which OS do you use? Do you use ubuntu as well? Since I was thinking that maybe this could be causing my issue?

no, I use debian, on a pi 4. but ubuntu does also work

**Comment by Helpme0822** [comment] 2024-04-28 14:37
When you tired to create your server using your method/egg did you actually do it on an oracle machine and it worked fine and got no errors? Or could there maybe be somekind of issue with the oracle servers that causes my issue? Since I'm using an oracle server

**Comment by QuintenQVD0** [comment] 2024-04-28 14:45
> When you tired to create your server using your method/egg did you actually try it once on an oracle machine and it worked fine and got no errors? Or could there maybe be somekind of issue with the oracle servers that causes my issue? Since I'm using an oracle server

I did try it on oracle, works fine, some chat modules may not work but it did just work.

**Comment by Helpme0822** [comment] 2024-04-28 14:48
> > When you tired to create your server using your method/egg did you actually try it once on an oracle machine and it worked fine and got no errors? Or could there maybe be somekind of issue with the oracle servers that causes my issue? Since I'm using an oracle server
> 
> I did try it on oracle, works fine, some chat modules may not work but it did just work.

Did you also actually try and join the server or waited like 5-10 minutes with the server being on? since the error appears either when someone joins the server and has finished loading in and spawns in the server or like every 5-10 minutes while the server is on

**Comment by Helpme0822** [comment] 2024-04-28 14:52
> > When you tired to create your server using your method/egg did you actually try it once on an oracle machine and it worked fine and got no errors? Or could there maybe be somekind of issue with the oracle servers that causes my issue? Since I'm using an oracle server
> 
> I did try it on oracle, works fine, some chat modules may not work but it did just work.

Also is it possible that voice chat doesn't work? Since I transferred my resources on my windows server to my oracle server and everything works fine except pma-voice. Like the Hud for the voice chat shows up but neither push to talk or voice activation works. I also checkedthe config of the resource if there was anything to change so it's compatible with the server but there isn't.

**Comment by QuintenQVD0** [comment] 2024-04-28 14:59
> > > When you tired to create your server using your method/egg did you actually try it once on an oracle machine and it worked fine and got no errors? Or could there maybe be somekind of issue with the oracle servers that causes my issue? Since I'm using an oracle server
> > 
> > 
> > I did try it on oracle, works fine, some chat modules may not work but it did just work.
> 
> Also is it possible that voice chat doesn't work? Since I transferred my resources on my windows server to my oracle server and everything works fine except pma-voice. Like the Hud for the voice chat shows up but neither push to talk or voice activation works. I also checkedthe config of the resource if there was anything to change so it's compatible with the server but there isn't.

some things can the emulator just not and it will not work then. some resources are windows only

**Comment by QuintenQVD0** [comment] 2024-05-08 12:56
> I have the same problem and apparently pma voice doesn't work either.

That some modules do not work, there is nothing I can do about that at all. That's just an emulator limitation.

**Comment by Helpme0822** [comment] 2024-05-08 15:55
> I have the same problem and apparently pma voice doesn't work either.

For me the error now randomly stopped appearing after using the server for a while. No idea why but I'm glad it's not there anymore. 

About pma-voice, I managed to make i work by hosting it externally on another website. Just google how to do it and you should find a tutorial on how to do it.

**Comment by PasswordOsa** [comment] 2024-05-08 21:41
> > I have the same problem and apparently pma voice doesn't work either.
> 
> For me the error now randomly stopped appearing after using the server for a while. No idea why but I'm glad it's not there anymore.
> 
> About pma-voice, I managed to make i work by hosting it externally on another server. Just google how to do it and you should find a tutorial on how to do it.

I managed to solve the problem by following this guide without using the egg. https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384 It seems that the problem is directly in the egg or in ptrodactyl in general.

**Comment by QuintenQVD0** [comment] 2024-05-09 05:36
> > > I have the same problem and apparently pma voice doesn't work either.
> > 
> > 
> > For me the error now randomly stopped appearing after using the server for a while. No idea why but I'm glad it's not there anymore.
> > About pma-voice, I managed to make i work by hosting it externally on another server. Just google how to do it and you should find a tutorial on how to do it.
> 
> I managed to solve the problem by following this guide without using the egg. https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384 It seems that the problem is directly in the egg or in ptrodactyl in general.

You realise the egg used the same emulator as in that guide? An was made before that guide was written? And the problem you all seem having is all network related because pterodactyl isolate all trafic and only allows use of the allocated ports.

**Comment by PasswordOsa** [comment] 2024-05-09 05:51
> > > > I have the same problem and apparently pma voice doesn't work either.
> > > 
> > > 
> > > For me the error now randomly stopped appearing after using the server for a while. No idea why but I'm glad it's not there anymore.
> > > About pma-voice, I managed to make i work by hosting it externally on another server. Just google how to do it and you should find a tutorial on how to do it.
> > 
> > 
> > I managed to solve the problem by following this guide without using the egg. https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384 It seems that the problem is directly in the egg or in ptrodactyl in general.
> 
> You realise the egg used the same emulator as in that guide? An was made before that guide was written? And the problem you all seem having is all network related because pterodactyl isolate all trafic and only allows use of the allocated ports.

That's why he points out that the problem must be in pterodactyl, a long time ago he had read in their discord that the panel was not always going to work well for all games.

**Comment by PasswordOsa** [comment] 2024-05-09 05:52
> > > > Tengo el mismo problema y al parecer la voz pma tampoco funciona.
> > > 
> > > 
> > > Para mí, el error ahora dejó de aparecer aleatoriamente después de usar el servidor por un tiempo.  No tengo idea de por qué, pero me alegro de que ya no esté allí. En cuanto a pma-voice, logré hacerlo funcionar alojándolo externamente en otro servidor.  Simplemente busque en Google cómo hacerlo y encontrará un tutorial sobre cómo hacerlo.
> > 
> > 
> > Logré resolver el problema siguiendo esta guía sin usar el huevo. [  https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384 ](https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384) Parece que el problema está directamente en el huevo o en el ptrodáctilo en general.
> 
> ¿Te das cuenta de que el huevo usó el mismo emulador que en esa guía? ¿Se hizo una antes de que se escribiera esa guía? Y el problema que todos parecen tener está relacionado con la red porque el pterodáctilo aísla todo el tráfico y solo permite el uso de los puertos asignados.

That's why he points out that the problem must be in pterodactyl, a long time ago he had read in their discord that the panel was not always going to work well for all games.

**Comment by PasswordOsa** [comment] 2024-05-09 05:53
> > > > Tengo el mismo problema y al parecer la voz pma tampoco funciona.
> > > 
> > > 
> > > Para mí, el error ahora dejó de aparecer aleatoriamente después de usar el servidor por un tiempo.  No tengo idea de por qué, pero me alegro de que ya no esté allí. En cuanto a pma-voice, logré hacerlo funcionar alojándolo externamente en otro servidor.  Simplemente busque en Google cómo hacerlo y encontrará un tutorial sobre cómo hacerlo.
> > 
> > 
> > Logré resolver el problema siguiendo esta guía sin usar el huevo. [  https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384 ](https://forum.cfx.re/t/deploying-a-fivem-server-in-ubuntu-on-aarch64-arm64-machine/5185384) Parece que el problema está directamente en el huevo o en el ptrodáctilo en general.
> 
> ¿Te das cuenta de que el huevo usó el mismo emulador que en esa guía? ¿Se hizo una antes de que se escribiera esa guía? Y el problema que todos parecen tener está relacionado con la red porque el pterodáctilo aísla todo el tráfico y solo permite el uso de los puertos asignados.

That's why I pointed out that the problem must be in pterodactyl, a long time ago I had read in their discord that the panel was not always going to work well for all games.

**Comment by QuintenQVD0** [comment] 2024-09-08 16:54
I am closing this as the egg works and those errors seem to be network related, if anyone want to have a further chat about that then feel free to comment here

**Closed by QuintenQVD0** 2024-09-08 16:54 UTC
